services:
  database_dev:
    image: 'postgres:17.2-alpine3.21'
    env_file:
      - .env.development
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  database_test:
    image: 'postgres:17.2-alpine3.21'
    env_file:
      - .env.test
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  backend:
